name: Test Docs
on:
  push:
    branches:
      - main
    paths:
      - docs/**/**.po
  pull_request:
    branches:
      - main
    paths:
      - docs/**/**.po
jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: Linux, python: '3.10', os: ubuntu-latest, tox: py310}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
          cache-dependency-path: 'requirements/*.txt'
      - name: update pip
        run: |
          pip install -U wheel
          pip install -U setuptools
          python -m pip install -U pip
      - run: pip install tox
      - run: tox -e docs
